### 모듈(Module)
- 파이선 코드를 논리적으로 묶어서 관리하고 사용할 수 있도록 하는 것
- 모듈 --> 파이선.py 파일이 하나의 모듈
- 기본 연결: import 모듈명 as 별명

- 하나의 모듈에 여러 함수들이 존재/ 이중 하나만 불러와서 사용하는 경우

from 모듈 명 import 함수명

In [ ]:
import pandas as pd

df = pd.DataFrame([[1,10,20,30], [2,40,50,60],[3,70,80,90]],
                  columns=["번호", "A", "B", "C"])
df

   번호   A   B   C
0   1  10  20  30
1   2  40  50  60
2   3  70  80  90

In [ ]:
from pandas import *

df = pd.DataFrame([[1,10,20,30], [2,40,50,60],[3,70,80,90]],
                  columns=["번호", "A", "B", "C"])
df

   번호   A   B   C
0   1  10  20  30
1   2  40  50  60
2   3  70  80  90

- 연결하는 모듈의 모든 함수를 모듈명 없이 사용
  *  from 모듈명 import *

In [ ]:
from google.colab import drive
drive.mount('/.content.drive')

Mounted at /.content.drive

In [ ]:
%cd /content/drive/MyDrive/Multi/python_class

/content/drive/MyDrive/Multi/python_class

In [ ]:
! pwd

/content/drive/MyDrive/Multi/python_class

- 사용자가 만든 모듈(사용자함수.py) 사용하기
  * 사용자 함수 파일 확장자: .py
  * 코드 실행 파일과 같은 폴더, 또는 하위 폴더
  * 개인 컴퓨터 (같은 폴더), 코랩은 하위 폴더
  * 코랩은 작업경로가 실행 파일 위치까지 cd로 이동하는 것이 좋다

In [ ]:
import sys
import csv

def openfile(fname):
    f = open(fname, "r")
    data = list(csv.reader(f))
    f.close()

    return data

if __name__ == "__main__":
  print(__name__)
  rdf = openfile("/content/drive/MyDrive/Multi/관광정보.csv")
  cnt = 0
  for line in rdf:
      cnt += 1
      print(line)
      if cnt == 10:
        break

__main__
['', '축제명', '주소', '연락처', '시작일', '종료일', '위도', '경도']
['0', '가락몰 페스티벌 2019', '서울특별시 송파구 양재대로 932', '02-3435-1000', '2019-10-11', '2019-10-12', '37.4960925880', '127.1109831778']
['1', '가리왕산 MUSIC FESTIVAL 2020', '강원도 정선군 북평면 중봉길 41-35', '033-560-3016', '2020-08-21', '2020-08-22', '37.4742535268', '128.6097538017']
['2', '가야문화축제 2020', '경상남도 김해시 가야의길 126', '055-330-3958', '2020-10-29', '2020-11-01', '35.2360687598', '128.8731002475']
['3', '가을 밀양강 오딧세이 "아리랑 환타지! 밀양!" 2019', '경상남도 밀양시 중앙로 324 영남루 및 밀양강 야외 공연장 일대', '055-359-4527', '2019-10-18', '2019-10-19', '35.4921350361', '128.7552590901']
['4', '가을 화담숲 단풍 축제 2019', '경기도 광주시 도척면 도척윗로 278', '031-8026-6666', '2019-10-12', '2019-11-10', '37.3374836915', '127.2922239974']
['5', '가을맥주페스타 2019', '부산광역시 부산진구 서면문화로 32 3,4층', '070-4880-2678', '2019-09-26', '2019-09-29', '35.1599862176', '129.0563669161']
['6', '가족사랑 걷기대회 2019', '부산광역시 사하구 낙동남로1233번길 1', '낙동강문화관 (연락처) 051-292-1042, 사하구건강가정지원센터 (연락처) 051-203-4588', '2019-09-28', '2019-09-28', '35.1083149990', '128.9474472484']
['7', '가족사랑 아이스축제 2019', '대구광역시 서구 문화로 122', '053-663-2184', '2019-07-27', '2019-07-27', '35.8736186548', '128.5454780875']
['8', '가족여행과 함께하는 고성 오션투유 삼포해수욕장 연날리기 축제 2019', '강원도 고성군 죽왕면 삼포리 1-1', '1666-5683', '2019-01-01', '2019-12-31', '38.3128520737', '128.5370623742']

In [ ]:
from modules import runfun

rdf=modules.runfun.openfile("/content/관광정보.csv")
print(rdf)

[['', '축제명', '주소', '연락처', '시작일', '종료일', '위도', '경도'], ['0', '가락몰 페스티벌 2019', '서울특별시 송파구 양재대로 932', '02-3435-1000', '2019-10-11', '2019-10-12', '37.4960925880', '127.1109831778'], ['1', '가리왕산 MUSIC FESTIVAL 2020', '강원도 정선군 북평면 중봉길 41-35', '033-560-3016', '2020-08-21', '2020-08-22', '37.4742535268', '128.6097538017'], ['2', '가야문화축제 2020', '경상남도 김해시 가야의길 126', '055-330-3958', '2020-10-29', '2020-11-01', '35.2360687598', '128.8731002475'], ['3', '가을 밀양강 오딧세이 "아리랑 환타지! 밀양!" 2019', '경상남도 밀양시 중앙로 324 영남루 및 밀양강 야외 공연장 일대', '055-359-4527', '2019-10-18', '2019-10-19', '35.4921350361', '128.7552590901'], ['4', '가을 화담숲 단풍 축제 2019', '경기도 광주시 도척면 도척윗로 278', '031-8026-6666', '2019-10-12', '2019-11-10', '37.3374836915', '127.2922239974'], ['5', '가을맥주페스타 2019', '부산광역시 부산진구 서면문화로 32 3,4층', '070-4880-2678', '2019-09-26', '2019-09-29', '35.1599862176', '129.0563669161'], ['6', '가족사랑 걷기대회 2019', '부산광역시 사하구 낙동남로1233번길 1', '낙동강문화관 (연락처) 051-292-1042, 사하구건강가정지원센터 (연락처) 051-203-4588', '2019-09-28', '2019-09-28', '35.1083149990', '128.9474472484'], ['7', '가족사랑 아이스축제 2019', '대구광역시 서구 문화로 122', '053-663-2184', '2019-07-27', '2019-07-27', '35.8736186548', '128.5454780875'], ['8', '가족여행과 함께하는 고성 오션투유 삼포해수욕장 연날리기 축제 2019', '강원도 고성군 죽왕면 삼포리 1-1', '1666-5683', '2019-01-01', '2019-12-31', '38.3128520737', '128.5370623742'], ['9', "가좌아트위크 '잠시, 쉬어가좌' 2019", '서울특별시 서대문구 증가로10길 28', '02-3140-8028', '2019-10-18', '2019-10-19', '37.5784852121', '126.9238923275'], ['10', '가평 자라섬 전국 막걸리 페스티벌 2019', '경기도 가평군 가평읍 달전리 1-1', '02-6080-6177', '2019-09-20', '2019-09-22', '37.8117052413', '127.5309525109'], ['11', '가평씽씽송어축제 2020', '경기도 가평군 가평읍 가평제방길 119', '031-581-6423', '2020-01-04', '2020-02-16', '37.8258616779', '127.5174061076'], ['12', '감물 및 봉숭아 물들이기 체험행사 2020', '제주특별자치도 서귀포시 표선면 민속해안로 631-34', '064-787-4501', '2020-07-24', '2020-08-02', '33.3213162956', '126.8431022619'], ['13', '감악문화축제 2019', '경기도 양주시 남면 감악산로244번길 189', '031-867-5683, 031-8082-7572', '2019-09-08', '2019-09-08', '37.8931800166', '126.9738399010'], ['14', '감악산 해맞이 2020', '경상남도 거창군 신원면', '010-2712-4482', '2020-01-01', '2020-01-01', '35.5953250627', '127.9274012896'], ['15', '갓바위소원성취축제 2019', '경산시 와촌면 대한리 갓바위 공영주차장', '053-851-0022', '2019-08-31', '2019-09-01', '35.9781440703', '128.7573259398'], ['16', '강남페스티벌 가로수길 그래피티 낙서해봐 2019', '서울특별시 강남구 도산대로13길', '02-576-5313', '2019-09-28', '2019-09-28', '37.5186022892', '127.0234738367'], ['17', '강동선사문화축제 2019', '서울특별시 강동구 올림픽로 875', '02-3425-5240', '2019-10-11', '2019-10-13', '37.5606243328', '127.1303240272'], ['18', '강동톡페스티벌 2019', '서울특별시 강동구 상암로 168', '강일 427-4004, 성내 471-0044, 해공 478-9656, 암사 429-0476, 천호 488-7223', '2019-11-02', '2019-11-02', '37.5457151498', '127.1412123500'], ['19', '강릉 관노가면극 2019', '강원도 강릉시 율곡로3139번길 24', '-', '2019-04-13', '2019-11-03', '37.7782679956', '128.8766149376'], ['20', '강릉 단오제 2020', '강원도 강릉시 단오장길 1', '033-641-1593', '2020-06-21', '2020-06-28', '37.7482134974', '128.8950169869'], ['21', '강릉 문화재야행 2020', '강원도 강릉시 임영로131번길 6', '033-823-3213', '2020-09-10', '2020-09-12', '37.7532267491', '128.8920698750'], ['22', '강릉 소금강산채마을 산채푸드페스티벌 2019', '강원도 강릉시 연곡면 소금강길 8', '033-660-3152', '2019-05-25', '2019-05-26', '37.8493286048', '128.7025117835'], ['23', '강릉 커피나무축제 2019', '강원도 강릉시 왕산면 왕산로 2171-19', '033-655-6644, 033-652-5599', '2019-05-30', '2019-06-02', '37.6522391209', '128.7848937448'], ['24', '강릉 하트불꽃크루즈 2020', '강원도 강릉시 주문진읍 해안로 1730', '1522-8905', '2020-01-01', '2020-12-31', '37.8895291758', '128.8285935985'], ['25', '강릉 K-POP콘서트 2019', '강원도 강릉시 종합운동장길 69', '033-640-2018', '2019-10-04', '2019-10-04', '37.7737772578', '128.8976131841'], ['26', '강릉국제영화제(GIFF) 2019', '강원도 강릉시 종합운동장길 84', '033-647-6807', '2019-11-08', '2019-11-14', '37.7716996777', '128.8954273345'], ['27', '강릉빙상스포츠페스티벌 2019', '강원도 강릉시 종합운동장길 32', '070-7791-3165', '2019-08-15', '2019-08-18', '37.7737410517', '128.8925247549'], ['28', '강릉소금강청학제 2019', '강원도 강릉시 연곡면 삼산리 56', '연곡면사무소 033-660-3681~2', '2019-10-12', '2019-10-13', '37.8136133361', '128.7044765951'], ['29', '강북구 근현대사 역사탐방여행 2019', '서울특별시 강북구 화계사길 117', '02-761-2588', '2019-04-13', '2019-10-20', '37.6325109780', '127.0070665450'], ['30', '강북구 산악문화제 2019', '서울특별시 강북구 우이동 186-5', '02-901-6227', '2019-09-21', '2019-09-21', '37.6615103869', '127.0072768111'], ['31', '강우방선생과 함께하는 한국회화의 금자탑, 민화 읽는 법 2019', '광주광역시 북구 하서로 110국립광주박물관', '062-570-7068', '2019-08-28', '2019-08-28', '35.1890917442', '126.8830624113'], ['32', '강원 국제 모터페스타 2019', '강원도 인제군 기린면 상하답로 130', '02-6740-7860', '2019-08-31', '2019-09-01', '38.0012086833', '128.2950634635'], ['33', '강원 산나물한마당축제 2019', '강원도 춘천시 평화로 1', '033-255-5458', '2019-04-26', '2019-04-28', '37.8855029718', '127.7215607554'], ['34', '강원과학기술대축전, 강원 지식재산 페스티벌 2019', '강원도 춘천시 서면 박사로 882', '070-7005-6870', '2019-09-06', '2019-09-07', '37.8951540906', '127.6927991992'], ['35', '강원그린박람회 2019', '강원도 춘천시 평화로 26', '033-260-9320', '2019-06-14', '2019-06-16', '37.8813589518', '127.7184944906'], ['36', '강진 영랑문학제 2019', '전라남도 강진군 강진읍 영랑생가길 15', '영랑기념사업회 061-434-0103', '2019-04-26', '2019-04-27', '34.6420874867', '126.7652585191'], ['37', '강진만 춤추는 갈대축제 2020', '전라남도 강진군 강진읍 남당로 97-111', '061-430-3352', '2020-10-23', '2020-11-01', '34.6201595364', '126.7739666192'], ['38', '강진청자축제 2020', '전라남도 강진군 대구면 청자촌길 33', '061-430-3352', '2020-10-08', '2020-10-13', '34.5075226164', '126.8011114048'], ['39', '강화 문화재 야행 2020', '인천 강화군 강화읍 관청리', '032-930-3515, 032-932-5464', '2020-09-11', '2020-09-12', '37.7487881453', '126.4855748369'], ['40', '강화 빙어축제 2020', '인천광역시 강화군 송해면 전망대로423번길 161', '032-933-3266', '2019-12-21', '2020-02-20', '37.8001841894', '126.4438577810'], ['41', '강화도 빙어, 송어 축제 2020', '인천광역시 강화군 내가면 고비고개로741번길 37-30', '032-933-1366', '2019-12-14', '2020-03-01', '37.7202402100', '126.4136461171'], ['42', '강화도 송어빙어축제 2020', '인천광역시 강화군 양도면 중앙로787번길 8-2', '010-6664-4354, 010-7617-6606', '2019-12-21', '2020-03-01', '37.6984402831', '126.4312173349'], ['43', '강화섬포도축제 2019', '인천광역시 강화군 길상면 초지리 1375-1, 초지대교 앞', '032-930-4140', '2019-09-21', '2019-09-22', '37.6264420922', '126.5307380038'], ['44', '개천절 대제전 2019', '서울특별시 종로구 인왕산로 22', '02-736-6375', '2019-10-03', '2019-10-03', '37.5758807095', '126.9657719166'], ['45', '개화산 해맞이 2020', '서울특별시 강서구 개화동', '02-2600-6455', '2020-01-01', '2020-01-01', '37.5821048853', '126.8047169862'], ['46', '거문도백도 은빛바다축제 2019', '전남 여수시 삼산면 거문리', '1899-2012', '2019-08-02', '2019-08-04', '34.0249238346', '127.3106896352'], ['47', '거제 대구 수산물축제 2019', '경상남도 거제시 장목면 외포5길 34', '055-369-4273', '2019-12-21', '2019-12-22', '34.9396463829', '128.7194799643'], ['48', '거제 바다로세계로 2019', '경상남도 거제시 계룡로11길 26', '055-639-4784', '2019-08-01', '2019-08-04', '34.8829397876', '128.6184763736'], ['49', '거제 어린이 축제 2019', '경상남도 거제시 계룡로11길 26', '055-639-3823', '2019-05-05', '2019-05-05', '34.8829397876', '128.6184763736']]

In [ ]:
from modules import modules   # 패키지 개념()

addf=modules.myfun.add(10,20)
print(addf)

ImportError: ignored

__name__ 변수
- 파이선에서 정한 의미있는 변수

In [ ]:
import modules.openfile.fileopen as ofs

rdf=ofs.openfile("/content/관광정보.csv")
print(rdf)

[['', '축제명', '주소', '연락처', '시작일', '종료일', '위도', '경도'], ['0', '가락몰 페스티벌 2019', '서울특별시 송파구 양재대로 932', '02-3435-1000', '2019-10-11', '2019-10-12', '37.4960925880', '127.1109831778'], ['1', '가리왕산 MUSIC FESTIVAL 2020', '강원도 정선군 북평면 중봉길 41-35', '033-560-3016', '2020-08-21', '2020-08-22', '37.4742535268', '128.6097538017'], ['2', '가야문화축제 2020', '경상남도 김해시 가야의길 126', '055-330-3958', '2020-10-29', '2020-11-01', '35.2360687598', '128.8731002475'], ['3', '가을 밀양강 오딧세이 "아리랑 환타지! 밀양!" 2019', '경상남도 밀양시 중앙로 324 영남루 및 밀양강 야외 공연장 일대', '055-359-4527', '2019-10-18', '2019-10-19', '35.4921350361', '128.7552590901'], ['4', '가을 화담숲 단풍 축제 2019', '경기도 광주시 도척면 도척윗로 278', '031-8026-6666', '2019-10-12', '2019-11-10', '37.3374836915', '127.2922239974'], ['5', '가을맥주페스타 2019', '부산광역시 부산진구 서면문화로 32 3,4층', '070-4880-2678', '2019-09-26', '2019-09-29', '35.1599862176', '129.0563669161'], ['6', '가족사랑 걷기대회 2019', '부산광역시 사하구 낙동남로1233번길 1', '낙동강문화관 (연락처) 051-292-1042, 사하구건강가정지원센터 (연락처) 051-203-4588', '2019-09-28', '2019-09-28', '35.1083149990', '128.9474472484'], ['7', '가족사랑 아이스축제 2019', '대구광역시 서구 문화로 122', '053-663-2184', '2019-07-27', '2019-07-27', '35.8736186548', '128.5454780875'], ['8', '가족여행과 함께하는 고성 오션투유 삼포해수욕장 연날리기 축제 2019', '강원도 고성군 죽왕면 삼포리 1-1', '1666-5683', '2019-01-01', '2019-12-31', '38.3128520737', '128.5370623742'], ['9', "가좌아트위크 '잠시, 쉬어가좌' 2019", '서울특별시 서대문구 증가로10길 28', '02-3140-8028', '2019-10-18', '2019-10-19', '37.5784852121', '126.9238923275'], ['10', '가평 자라섬 전국 막걸리 페스티벌 2019', '경기도 가평군 가평읍 달전리 1-1', '02-6080-6177', '2019-09-20', '2019-09-22', '37.8117052413', '127.5309525109'], ['11', '가평씽씽송어축제 2020', '경기도 가평군 가평읍 가평제방길 119', '031-581-6423', '2020-01-04', '2020-02-16', '37.8258616779', '127.5174061076'], ['12', '감물 및 봉숭아 물들이기 체험행사 2020', '제주특별자치도 서귀포시 표선면 민속해안로 631-34', '064-787-4501', '2020-07-24', '2020-08-02', '33.3213162956', '126.8431022619'], ['13', '감악문화축제 2019', '경기도 양주시 남면 감악산로244번길 189', '031-867-5683, 031-8082-7572', '2019-09-08', '2019-09-08', '37.8931800166', '126.9738399010'], ['14', '감악산 해맞이 2020', '경상남도 거창군 신원면', '010-2712-4482', '2020-01-01', '2020-01-01', '35.5953250627', '127.9274012896'], ['15', '갓바위소원성취축제 2019', '경산시 와촌면 대한리 갓바위 공영주차장', '053-851-0022', '2019-08-31', '2019-09-01', '35.9781440703', '128.7573259398'], ['16', '강남페스티벌 가로수길 그래피티 낙서해봐 2019', '서울특별시 강남구 도산대로13길', '02-576-5313', '2019-09-28', '2019-09-28', '37.5186022892', '127.0234738367'], ['17', '강동선사문화축제 2019', '서울특별시 강동구 올림픽로 875', '02-3425-5240', '2019-10-11', '2019-10-13', '37.5606243328', '127.1303240272'], ['18', '강동톡페스티벌 2019', '서울특별시 강동구 상암로 168', '강일 427-4004, 성내 471-0044, 해공 478-9656, 암사 429-0476, 천호 488-7223', '2019-11-02', '2019-11-02', '37.5457151498', '127.1412123500'], ['19', '강릉 관노가면극 2019', '강원도 강릉시 율곡로3139번길 24', '-', '2019-04-13', '2019-11-03', '37.7782679956', '128.8766149376'], ['20', '강릉 단오제 2020', '강원도 강릉시 단오장길 1', '033-641-1593', '2020-06-21', '2020-06-28', '37.7482134974', '128.8950169869'], ['21', '강릉 문화재야행 2020', '강원도 강릉시 임영로131번길 6', '033-823-3213', '2020-09-10', '2020-09-12', '37.7532267491', '128.8920698750'], ['22', '강릉 소금강산채마을 산채푸드페스티벌 2019', '강원도 강릉시 연곡면 소금강길 8', '033-660-3152', '2019-05-25', '2019-05-26', '37.8493286048', '128.7025117835'], ['23', '강릉 커피나무축제 2019', '강원도 강릉시 왕산면 왕산로 2171-19', '033-655-6644, 033-652-5599', '2019-05-30', '2019-06-02', '37.6522391209', '128.7848937448'], ['24', '강릉 하트불꽃크루즈 2020', '강원도 강릉시 주문진읍 해안로 1730', '1522-8905', '2020-01-01', '2020-12-31', '37.8895291758', '128.8285935985'], ['25', '강릉 K-POP콘서트 2019', '강원도 강릉시 종합운동장길 69', '033-640-2018', '2019-10-04', '2019-10-04', '37.7737772578', '128.8976131841'], ['26', '강릉국제영화제(GIFF) 2019', '강원도 강릉시 종합운동장길 84', '033-647-6807', '2019-11-08', '2019-11-14', '37.7716996777', '128.8954273345'], ['27', '강릉빙상스포츠페스티벌 2019', '강원도 강릉시 종합운동장길 32', '070-7791-3165', '2019-08-15', '2019-08-18', '37.7737410517', '128.8925247549'], ['28', '강릉소금강청학제 2019', '강원도 강릉시 연곡면 삼산리 56', '연곡면사무소 033-660-3681~2', '2019-10-12', '2019-10-13', '37.8136133361', '128.7044765951'], ['29', '강북구 근현대사 역사탐방여행 2019', '서울특별시 강북구 화계사길 117', '02-761-2588', '2019-04-13', '2019-10-20', '37.6325109780', '127.0070665450'], ['30', '강북구 산악문화제 2019', '서울특별시 강북구 우이동 186-5', '02-901-6227', '2019-09-21', '2019-09-21', '37.6615103869', '127.0072768111'], ['31', '강우방선생과 함께하는 한국회화의 금자탑, 민화 읽는 법 2019', '광주광역시 북구 하서로 110국립광주박물관', '062-570-7068', '2019-08-28', '2019-08-28', '35.1890917442', '126.8830624113'], ['32', '강원 국제 모터페스타 2019', '강원도 인제군 기린면 상하답로 130', '02-6740-7860', '2019-08-31', '2019-09-01', '38.0012086833', '128.2950634635'], ['33', '강원 산나물한마당축제 2019', '강원도 춘천시 평화로 1', '033-255-5458', '2019-04-26', '2019-04-28', '37.8855029718', '127.7215607554'], ['34', '강원과학기술대축전, 강원 지식재산 페스티벌 2019', '강원도 춘천시 서면 박사로 882', '070-7005-6870', '2019-09-06', '2019-09-07', '37.8951540906', '127.6927991992'], ['35', '강원그린박람회 2019', '강원도 춘천시 평화로 26', '033-260-9320', '2019-06-14', '2019-06-16', '37.8813589518', '127.7184944906'], ['36', '강진 영랑문학제 2019', '전라남도 강진군 강진읍 영랑생가길 15', '영랑기념사업회 061-434-0103', '2019-04-26', '2019-04-27', '34.6420874867', '126.7652585191'], ['37', '강진만 춤추는 갈대축제 2020', '전라남도 강진군 강진읍 남당로 97-111', '061-430-3352', '2020-10-23', '2020-11-01', '34.6201595364', '126.7739666192'], ['38', '강진청자축제 2020', '전라남도 강진군 대구면 청자촌길 33', '061-430-3352', '2020-10-08', '2020-10-13', '34.5075226164', '126.8011114048'], ['39', '강화 문화재 야행 2020', '인천 강화군 강화읍 관청리', '032-930-3515, 032-932-5464', '2020-09-11', '2020-09-12', '37.7487881453', '126.4855748369'], ['40', '강화 빙어축제 2020', '인천광역시 강화군 송해면 전망대로423번길 161', '032-933-3266', '2019-12-21', '2020-02-20', '37.8001841894', '126.4438577810'], ['41', '강화도 빙어, 송어 축제 2020', '인천광역시 강화군 내가면 고비고개로741번길 37-30', '032-933-1366', '2019-12-14', '2020-03-01', '37.7202402100', '126.4136461171'], ['42', '강화도 송어빙어축제 2020', '인천광역시 강화군 양도면 중앙로787번길 8-2', '010-6664-4354, 010-7617-6606', '2019-12-21', '2020-03-01', '37.6984402831', '126.4312173349'], ['43', '강화섬포도축제 2019', '인천광역시 강화군 길상면 초지리 1375-1, 초지대교 앞', '032-930-4140', '2019-09-21', '2019-09-22', '37.6264420922', '126.5307380038'], ['44', '개천절 대제전 2019', '서울특별시 종로구 인왕산로 22', '02-736-6375', '2019-10-03', '2019-10-03', '37.5758807095', '126.9657719166'], ['45', '개화산 해맞이 2020', '서울특별시 강서구 개화동', '02-2600-6455', '2020-01-01', '2020-01-01', '37.5821048853', '126.8047169862'], ['46', '거문도백도 은빛바다축제 2019', '전남 여수시 삼산면 거문리', '1899-2012', '2019-08-02', '2019-08-04', '34.0249238346', '127.3106896352'], ['47', '거제 대구 수산물축제 2019', '경상남도 거제시 장목면 외포5길 34', '055-369-4273', '2019-12-21', '2019-12-22', '34.9396463829', '128.7194799643'], ['48', '거제 바다로세계로 2019', '경상남도 거제시 계룡로11길 26', '055-639-4784', '2019-08-01', '2019-08-04', '34.8829397876', '128.6184763736'], ['49', '거제 어린이 축제 2019', '경상남도 거제시 계룡로11길 26', '055-639-3823', '2019-05-05', '2019-05-05', '34.8829397876', '128.6184763736']]

In [ ]:
from modules.openfile import fileopen

rdf=fileopen.openfile("/content/관광정보.csv")
print(rdf)

[['', '축제명', '주소', '연락처', '시작일', '종료일', '위도', '경도'], ['0', '가락몰 페스티벌 2019', '서울특별시 송파구 양재대로 932', '02-3435-1000', '2019-10-11', '2019-10-12', '37.4960925880', '127.1109831778'], ['1', '가리왕산 MUSIC FESTIVAL 2020', '강원도 정선군 북평면 중봉길 41-35', '033-560-3016', '2020-08-21', '2020-08-22', '37.4742535268', '128.6097538017'], ['2', '가야문화축제 2020', '경상남도 김해시 가야의길 126', '055-330-3958', '2020-10-29', '2020-11-01', '35.2360687598', '128.8731002475'], ['3', '가을 밀양강 오딧세이 "아리랑 환타지! 밀양!" 2019', '경상남도 밀양시 중앙로 324 영남루 및 밀양강 야외 공연장 일대', '055-359-4527', '2019-10-18', '2019-10-19', '35.4921350361', '128.7552590901'], ['4', '가을 화담숲 단풍 축제 2019', '경기도 광주시 도척면 도척윗로 278', '031-8026-6666', '2019-10-12', '2019-11-10', '37.3374836915', '127.2922239974'], ['5', '가을맥주페스타 2019', '부산광역시 부산진구 서면문화로 32 3,4층', '070-4880-2678', '2019-09-26', '2019-09-29', '35.1599862176', '129.0563669161'], ['6', '가족사랑 걷기대회 2019', '부산광역시 사하구 낙동남로1233번길 1', '낙동강문화관 (연락처) 051-292-1042, 사하구건강가정지원센터 (연락처) 051-203-4588', '2019-09-28', '2019-09-28', '35.1083149990', '128.9474472484'], ['7', '가족사랑 아이스축제 2019', '대구광역시 서구 문화로 122', '053-663-2184', '2019-07-27', '2019-07-27', '35.8736186548', '128.5454780875'], ['8', '가족여행과 함께하는 고성 오션투유 삼포해수욕장 연날리기 축제 2019', '강원도 고성군 죽왕면 삼포리 1-1', '1666-5683', '2019-01-01', '2019-12-31', '38.3128520737', '128.5370623742'], ['9', "가좌아트위크 '잠시, 쉬어가좌' 2019", '서울특별시 서대문구 증가로10길 28', '02-3140-8028', '2019-10-18', '2019-10-19', '37.5784852121', '126.9238923275'], ['10', '가평 자라섬 전국 막걸리 페스티벌 2019', '경기도 가평군 가평읍 달전리 1-1', '02-6080-6177', '2019-09-20', '2019-09-22', '37.8117052413', '127.5309525109'], ['11', '가평씽씽송어축제 2020', '경기도 가평군 가평읍 가평제방길 119', '031-581-6423', '2020-01-04', '2020-02-16', '37.8258616779', '127.5174061076'], ['12', '감물 및 봉숭아 물들이기 체험행사 2020', '제주특별자치도 서귀포시 표선면 민속해안로 631-34', '064-787-4501', '2020-07-24', '2020-08-02', '33.3213162956', '126.8431022619'], ['13', '감악문화축제 2019', '경기도 양주시 남면 감악산로244번길 189', '031-867-5683, 031-8082-7572', '2019-09-08', '2019-09-08', '37.8931800166', '126.9738399010'], ['14', '감악산 해맞이 2020', '경상남도 거창군 신원면', '010-2712-4482', '2020-01-01', '2020-01-01', '35.5953250627', '127.9274012896'], ['15', '갓바위소원성취축제 2019', '경산시 와촌면 대한리 갓바위 공영주차장', '053-851-0022', '2019-08-31', '2019-09-01', '35.9781440703', '128.7573259398'], ['16', '강남페스티벌 가로수길 그래피티 낙서해봐 2019', '서울특별시 강남구 도산대로13길', '02-576-5313', '2019-09-28', '2019-09-28', '37.5186022892', '127.0234738367'], ['17', '강동선사문화축제 2019', '서울특별시 강동구 올림픽로 875', '02-3425-5240', '2019-10-11', '2019-10-13', '37.5606243328', '127.1303240272'], ['18', '강동톡페스티벌 2019', '서울특별시 강동구 상암로 168', '강일 427-4004, 성내 471-0044, 해공 478-9656, 암사 429-0476, 천호 488-7223', '2019-11-02', '2019-11-02', '37.5457151498', '127.1412123500'], ['19', '강릉 관노가면극 2019', '강원도 강릉시 율곡로3139번길 24', '-', '2019-04-13', '2019-11-03', '37.7782679956', '128.8766149376'], ['20', '강릉 단오제 2020', '강원도 강릉시 단오장길 1', '033-641-1593', '2020-06-21', '2020-06-28', '37.7482134974', '128.8950169869'], ['21', '강릉 문화재야행 2020', '강원도 강릉시 임영로131번길 6', '033-823-3213', '2020-09-10', '2020-09-12', '37.7532267491', '128.8920698750'], ['22', '강릉 소금강산채마을 산채푸드페스티벌 2019', '강원도 강릉시 연곡면 소금강길 8', '033-660-3152', '2019-05-25', '2019-05-26', '37.8493286048', '128.7025117835'], ['23', '강릉 커피나무축제 2019', '강원도 강릉시 왕산면 왕산로 2171-19', '033-655-6644, 033-652-5599', '2019-05-30', '2019-06-02', '37.6522391209', '128.7848937448'], ['24', '강릉 하트불꽃크루즈 2020', '강원도 강릉시 주문진읍 해안로 1730', '1522-8905', '2020-01-01', '2020-12-31', '37.8895291758', '128.8285935985'], ['25', '강릉 K-POP콘서트 2019', '강원도 강릉시 종합운동장길 69', '033-640-2018', '2019-10-04', '2019-10-04', '37.7737772578', '128.8976131841'], ['26', '강릉국제영화제(GIFF) 2019', '강원도 강릉시 종합운동장길 84', '033-647-6807', '2019-11-08', '2019-11-14', '37.7716996777', '128.8954273345'], ['27', '강릉빙상스포츠페스티벌 2019', '강원도 강릉시 종합운동장길 32', '070-7791-3165', '2019-08-15', '2019-08-18', '37.7737410517', '128.8925247549'], ['28', '강릉소금강청학제 2019', '강원도 강릉시 연곡면 삼산리 56', '연곡면사무소 033-660-3681~2', '2019-10-12', '2019-10-13', '37.8136133361', '128.7044765951'], ['29', '강북구 근현대사 역사탐방여행 2019', '서울특별시 강북구 화계사길 117', '02-761-2588', '2019-04-13', '2019-10-20', '37.6325109780', '127.0070665450'], ['30', '강북구 산악문화제 2019', '서울특별시 강북구 우이동 186-5', '02-901-6227', '2019-09-21', '2019-09-21', '37.6615103869', '127.0072768111'], ['31', '강우방선생과 함께하는 한국회화의 금자탑, 민화 읽는 법 2019', '광주광역시 북구 하서로 110국립광주박물관', '062-570-7068', '2019-08-28', '2019-08-28', '35.1890917442', '126.8830624113'], ['32', '강원 국제 모터페스타 2019', '강원도 인제군 기린면 상하답로 130', '02-6740-7860', '2019-08-31', '2019-09-01', '38.0012086833', '128.2950634635'], ['33', '강원 산나물한마당축제 2019', '강원도 춘천시 평화로 1', '033-255-5458', '2019-04-26', '2019-04-28', '37.8855029718', '127.7215607554'], ['34', '강원과학기술대축전, 강원 지식재산 페스티벌 2019', '강원도 춘천시 서면 박사로 882', '070-7005-6870', '2019-09-06', '2019-09-07', '37.8951540906', '127.6927991992'], ['35', '강원그린박람회 2019', '강원도 춘천시 평화로 26', '033-260-9320', '2019-06-14', '2019-06-16', '37.8813589518', '127.7184944906'], ['36', '강진 영랑문학제 2019', '전라남도 강진군 강진읍 영랑생가길 15', '영랑기념사업회 061-434-0103', '2019-04-26', '2019-04-27', '34.6420874867', '126.7652585191'], ['37', '강진만 춤추는 갈대축제 2020', '전라남도 강진군 강진읍 남당로 97-111', '061-430-3352', '2020-10-23', '2020-11-01', '34.6201595364', '126.7739666192'], ['38', '강진청자축제 2020', '전라남도 강진군 대구면 청자촌길 33', '061-430-3352', '2020-10-08', '2020-10-13', '34.5075226164', '126.8011114048'], ['39', '강화 문화재 야행 2020', '인천 강화군 강화읍 관청리', '032-930-3515, 032-932-5464', '2020-09-11', '2020-09-12', '37.7487881453', '126.4855748369'], ['40', '강화 빙어축제 2020', '인천광역시 강화군 송해면 전망대로423번길 161', '032-933-3266', '2019-12-21', '2020-02-20', '37.8001841894', '126.4438577810'], ['41', '강화도 빙어, 송어 축제 2020', '인천광역시 강화군 내가면 고비고개로741번길 37-30', '032-933-1366', '2019-12-14', '2020-03-01', '37.7202402100', '126.4136461171'], ['42', '강화도 송어빙어축제 2020', '인천광역시 강화군 양도면 중앙로787번길 8-2', '010-6664-4354, 010-7617-6606', '2019-12-21', '2020-03-01', '37.6984402831', '126.4312173349'], ['43', '강화섬포도축제 2019', '인천광역시 강화군 길상면 초지리 1375-1, 초지대교 앞', '032-930-4140', '2019-09-21', '2019-09-22', '37.6264420922', '126.5307380038'], ['44', '개천절 대제전 2019', '서울특별시 종로구 인왕산로 22', '02-736-6375', '2019-10-03', '2019-10-03', '37.5758807095', '126.9657719166'], ['45', '개화산 해맞이 2020', '서울특별시 강서구 개화동', '02-2600-6455', '2020-01-01', '2020-01-01', '37.5821048853', '126.8047169862'], ['46', '거문도백도 은빛바다축제 2019', '전남 여수시 삼산면 거문리', '1899-2012', '2019-08-02', '2019-08-04', '34.0249238346', '127.3106896352'], ['47', '거제 대구 수산물축제 2019', '경상남도 거제시 장목면 외포5길 34', '055-369-4273', '2019-12-21', '2019-12-22', '34.9396463829', '128.7194799643'], ['48', '거제 바다로세계로 2019', '경상남도 거제시 계룡로11길 26', '055-639-4784', '2019-08-01', '2019-08-04', '34.8829397876', '128.6184763736'], ['49', '거제 어린이 축제 2019', '경상남도 거제시 계룡로11길 26', '055-639-3823', '2019-05-05', '2019-05-05', '34.8829397876', '128.6184763736']]

In [ ]:
from modules import openfile

rdf=openfile.fileopen.openfile("/content/관광정보.csv")
print(rdf)

[['', '축제명', '주소', '연락처', '시작일', '종료일', '위도', '경도'], ['0', '가락몰 페스티벌 2019', '서울특별시 송파구 양재대로 932', '02-3435-1000', '2019-10-11', '2019-10-12', '37.4960925880', '127.1109831778'], ['1', '가리왕산 MUSIC FESTIVAL 2020', '강원도 정선군 북평면 중봉길 41-35', '033-560-3016', '2020-08-21', '2020-08-22', '37.4742535268', '128.6097538017'], ['2', '가야문화축제 2020', '경상남도 김해시 가야의길 126', '055-330-3958', '2020-10-29', '2020-11-01', '35.2360687598', '128.8731002475'], ['3', '가을 밀양강 오딧세이 "아리랑 환타지! 밀양!" 2019', '경상남도 밀양시 중앙로 324 영남루 및 밀양강 야외 공연장 일대', '055-359-4527', '2019-10-18', '2019-10-19', '35.4921350361', '128.7552590901'], ['4', '가을 화담숲 단풍 축제 2019', '경기도 광주시 도척면 도척윗로 278', '031-8026-6666', '2019-10-12', '2019-11-10', '37.3374836915', '127.2922239974'], ['5', '가을맥주페스타 2019', '부산광역시 부산진구 서면문화로 32 3,4층', '070-4880-2678', '2019-09-26', '2019-09-29', '35.1599862176', '129.0563669161'], ['6', '가족사랑 걷기대회 2019', '부산광역시 사하구 낙동남로1233번길 1', '낙동강문화관 (연락처) 051-292-1042, 사하구건강가정지원센터 (연락처) 051-203-4588', '2019-09-28', '2019-09-28', '35.1083149990', '128.9474472484'], ['7', '가족사랑 아이스축제 2019', '대구광역시 서구 문화로 122', '053-663-2184', '2019-07-27', '2019-07-27', '35.8736186548', '128.5454780875'], ['8', '가족여행과 함께하는 고성 오션투유 삼포해수욕장 연날리기 축제 2019', '강원도 고성군 죽왕면 삼포리 1-1', '1666-5683', '2019-01-01', '2019-12-31', '38.3128520737', '128.5370623742'], ['9', "가좌아트위크 '잠시, 쉬어가좌' 2019", '서울특별시 서대문구 증가로10길 28', '02-3140-8028', '2019-10-18', '2019-10-19', '37.5784852121', '126.9238923275'], ['10', '가평 자라섬 전국 막걸리 페스티벌 2019', '경기도 가평군 가평읍 달전리 1-1', '02-6080-6177', '2019-09-20', '2019-09-22', '37.8117052413', '127.5309525109'], ['11', '가평씽씽송어축제 2020', '경기도 가평군 가평읍 가평제방길 119', '031-581-6423', '2020-01-04', '2020-02-16', '37.8258616779', '127.5174061076'], ['12', '감물 및 봉숭아 물들이기 체험행사 2020', '제주특별자치도 서귀포시 표선면 민속해안로 631-34', '064-787-4501', '2020-07-24', '2020-08-02', '33.3213162956', '126.8431022619'], ['13', '감악문화축제 2019', '경기도 양주시 남면 감악산로244번길 189', '031-867-5683, 031-8082-7572', '2019-09-08', '2019-09-08', '37.8931800166', '126.9738399010'], ['14', '감악산 해맞이 2020', '경상남도 거창군 신원면', '010-2712-4482', '2020-01-01', '2020-01-01', '35.5953250627', '127.9274012896'], ['15', '갓바위소원성취축제 2019', '경산시 와촌면 대한리 갓바위 공영주차장', '053-851-0022', '2019-08-31', '2019-09-01', '35.9781440703', '128.7573259398'], ['16', '강남페스티벌 가로수길 그래피티 낙서해봐 2019', '서울특별시 강남구 도산대로13길', '02-576-5313', '2019-09-28', '2019-09-28', '37.5186022892', '127.0234738367'], ['17', '강동선사문화축제 2019', '서울특별시 강동구 올림픽로 875', '02-3425-5240', '2019-10-11', '2019-10-13', '37.5606243328', '127.1303240272'], ['18', '강동톡페스티벌 2019', '서울특별시 강동구 상암로 168', '강일 427-4004, 성내 471-0044, 해공 478-9656, 암사 429-0476, 천호 488-7223', '2019-11-02', '2019-11-02', '37.5457151498', '127.1412123500'], ['19', '강릉 관노가면극 2019', '강원도 강릉시 율곡로3139번길 24', '-', '2019-04-13', '2019-11-03', '37.7782679956', '128.8766149376'], ['20', '강릉 단오제 2020', '강원도 강릉시 단오장길 1', '033-641-1593', '2020-06-21', '2020-06-28', '37.7482134974', '128.8950169869'], ['21', '강릉 문화재야행 2020', '강원도 강릉시 임영로131번길 6', '033-823-3213', '2020-09-10', '2020-09-12', '37.7532267491', '128.8920698750'], ['22', '강릉 소금강산채마을 산채푸드페스티벌 2019', '강원도 강릉시 연곡면 소금강길 8', '033-660-3152', '2019-05-25', '2019-05-26', '37.8493286048', '128.7025117835'], ['23', '강릉 커피나무축제 2019', '강원도 강릉시 왕산면 왕산로 2171-19', '033-655-6644, 033-652-5599', '2019-05-30', '2019-06-02', '37.6522391209', '128.7848937448'], ['24', '강릉 하트불꽃크루즈 2020', '강원도 강릉시 주문진읍 해안로 1730', '1522-8905', '2020-01-01', '2020-12-31', '37.8895291758', '128.8285935985'], ['25', '강릉 K-POP콘서트 2019', '강원도 강릉시 종합운동장길 69', '033-640-2018', '2019-10-04', '2019-10-04', '37.7737772578', '128.8976131841'], ['26', '강릉국제영화제(GIFF) 2019', '강원도 강릉시 종합운동장길 84', '033-647-6807', '2019-11-08', '2019-11-14', '37.7716996777', '128.8954273345'], ['27', '강릉빙상스포츠페스티벌 2019', '강원도 강릉시 종합운동장길 32', '070-7791-3165', '2019-08-15', '2019-08-18', '37.7737410517', '128.8925247549'], ['28', '강릉소금강청학제 2019', '강원도 강릉시 연곡면 삼산리 56', '연곡면사무소 033-660-3681~2', '2019-10-12', '2019-10-13', '37.8136133361', '128.7044765951'], ['29', '강북구 근현대사 역사탐방여행 2019', '서울특별시 강북구 화계사길 117', '02-761-2588', '2019-04-13', '2019-10-20', '37.6325109780', '127.0070665450'], ['30', '강북구 산악문화제 2019', '서울특별시 강북구 우이동 186-5', '02-901-6227', '2019-09-21', '2019-09-21', '37.6615103869', '127.0072768111'], ['31', '강우방선생과 함께하는 한국회화의 금자탑, 민화 읽는 법 2019', '광주광역시 북구 하서로 110국립광주박물관', '062-570-7068', '2019-08-28', '2019-08-28', '35.1890917442', '126.8830624113'], ['32', '강원 국제 모터페스타 2019', '강원도 인제군 기린면 상하답로 130', '02-6740-7860', '2019-08-31', '2019-09-01', '38.0012086833', '128.2950634635'], ['33', '강원 산나물한마당축제 2019', '강원도 춘천시 평화로 1', '033-255-5458', '2019-04-26', '2019-04-28', '37.8855029718', '127.7215607554'], ['34', '강원과학기술대축전, 강원 지식재산 페스티벌 2019', '강원도 춘천시 서면 박사로 882', '070-7005-6870', '2019-09-06', '2019-09-07', '37.8951540906', '127.6927991992'], ['35', '강원그린박람회 2019', '강원도 춘천시 평화로 26', '033-260-9320', '2019-06-14', '2019-06-16', '37.8813589518', '127.7184944906'], ['36', '강진 영랑문학제 2019', '전라남도 강진군 강진읍 영랑생가길 15', '영랑기념사업회 061-434-0103', '2019-04-26', '2019-04-27', '34.6420874867', '126.7652585191'], ['37', '강진만 춤추는 갈대축제 2020', '전라남도 강진군 강진읍 남당로 97-111', '061-430-3352', '2020-10-23', '2020-11-01', '34.6201595364', '126.7739666192'], ['38', '강진청자축제 2020', '전라남도 강진군 대구면 청자촌길 33', '061-430-3352', '2020-10-08', '2020-10-13', '34.5075226164', '126.8011114048'], ['39', '강화 문화재 야행 2020', '인천 강화군 강화읍 관청리', '032-930-3515, 032-932-5464', '2020-09-11', '2020-09-12', '37.7487881453', '126.4855748369'], ['40', '강화 빙어축제 2020', '인천광역시 강화군 송해면 전망대로423번길 161', '032-933-3266', '2019-12-21', '2020-02-20', '37.8001841894', '126.4438577810'], ['41', '강화도 빙어, 송어 축제 2020', '인천광역시 강화군 내가면 고비고개로741번길 37-30', '032-933-1366', '2019-12-14', '2020-03-01', '37.7202402100', '126.4136461171'], ['42', '강화도 송어빙어축제 2020', '인천광역시 강화군 양도면 중앙로787번길 8-2', '010-6664-4354, 010-7617-6606', '2019-12-21', '2020-03-01', '37.6984402831', '126.4312173349'], ['43', '강화섬포도축제 2019', '인천광역시 강화군 길상면 초지리 1375-1, 초지대교 앞', '032-930-4140', '2019-09-21', '2019-09-22', '37.6264420922', '126.5307380038'], ['44', '개천절 대제전 2019', '서울특별시 종로구 인왕산로 22', '02-736-6375', '2019-10-03', '2019-10-03', '37.5758807095', '126.9657719166'], ['45', '개화산 해맞이 2020', '서울특별시 강서구 개화동', '02-2600-6455', '2020-01-01', '2020-01-01', '37.5821048853', '126.8047169862'], ['46', '거문도백도 은빛바다축제 2019', '전남 여수시 삼산면 거문리', '1899-2012', '2019-08-02', '2019-08-04', '34.0249238346', '127.3106896352'], ['47', '거제 대구 수산물축제 2019', '경상남도 거제시 장목면 외포5길 34', '055-369-4273', '2019-12-21', '2019-12-22', '34.9396463829', '128.7194799643'], ['48', '거제 바다로세계로 2019', '경상남도 거제시 계룡로11길 26', '055-639-4784', '2019-08-01', '2019-08-04', '34.8829397876', '128.6184763736'], ['49', '거제 어린이 축제 2019', '경상남도 거제시 계룡로11길 26', '055-639-3823', '2019-05-05', '2019-05-05', '34.8829397876', '128.6184763736']]

In [ ]:
### content
!pwd

/content

In [ ]:
import csv #csv 모듈 임포트
f = open("/content/관광정보.csv","r",encoding="cp949") #csv 파일 열어라

data = list(csv.reader(f))
f.close()

data[:5]

UnicodeDecodeError: ignored