Html 태그 참조
- https://ofcourse.kr/html-course/HTML-%EC%9E%85%EB%AC%B8

구글맵 API 체험
- 구글맵 API 가입
- 참고: https://cloud.google.com/maps-platform/
- 참고: https://tinyurl.com/y3uw2ppf

In [ ]:
#!pip install googlemaps
import googlemaps  # 데이터는 Json 형식(딕셔너리)으로 제공

user_Key='AIzaSyB8Ua6RAi-ZC5WoE4xbEtlnEWZ_XOpaWGk'
gmaps=googlemaps.Client(key=user_Key)

sch=input("조회할 명칭이나 주소를 입력하세요:")
ggmp=gmaps.geocode(sch, language='ko')
ggmp

조회할 명칭이나 주소를 입력하세요:강남구청

[{'address_components': [{'long_name': '강남구',
    'short_name': '강남구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']}],
  'formatted_address': '대한민국 서울특별시 강남구',
  'geometry': {'bounds': {'northeast': {'lat': 37.5373614, 'lng': 127.1244733},
    'southwest': {'lat': 37.4563361, 'lng': 127.0114055}},
   'location': {'lat': 37.5172363, 'lng': 127.0473248},
   'location_type': 'APPROXIMATE',
   'viewport': {'northeast': {'lat': 37.5373614, 'lng': 127.1244733},
    'southwest': {'lat': 37.4563361, 'lng': 127.0114055}}},
  'place_id': 'ChIJ-4m1XyOkfDURartwxRuXMbM',
  'types': ['political', 'sublocality', 'sublocality_level_1']}]

In [ ]:
print("주소:", ggmp[0]['formatted_address'])
print(ggmp[0]['geometry'])
print()
print(ggmp[0]['geometry']['location'])
print()
print(ggmp[0]['geometry']['location']['lat'])
print(ggmp[0]['geometry']['location']['lng'])

주소: 대한민국 서울특별시 서초구 서초동 393-1
{'location': {'lat': 37.4795371, 'lng': 127.0218775}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.4808860802915, 'lng': 127.0232264802915}, 'southwest': {'lat': 37.47818811970851, 'lng': 127.0205285197085}}}

{'lat': 37.4795371, 'lng': 127.0218775}

37.4795371
127.0218775

유가정보를 이용한 지도 그리기

In [ ]:
#!pip install folium
#!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [ ]:
import pandas as pd
import folium
import googlemaps
from glob import glob

# c:/pydata 폴더에서 원하는 파일만 추출해 리스트로 제공
filenames=glob("c:/pydata/*주유소*.xls")

df=pd.DataFrame()

for fname in filenames:
    tmp=pd.read_excel(fname, header=2)
    df=pd.concat([df, tmp])

df=df.reset_index(drop=True)

In [ ]:
df.head()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      76 non-null     object
 1   상호      76 non-null     object
 2   주소      76 non-null     object
 3   상표      76 non-null     object
 4   전화번호    76 non-null     object
 5   셀프여부    76 non-null     object
 6   고급휘발유   76 non-null     object
 7   휘발유     76 non-null     object
 8   경유      76 non-null     object
 9   실내등유    76 non-null     object
dtypes: object(10)
memory usage: 6.1+ KB

In [ ]:
# df에서 ["상호","주소","상표", "휘발유"] 만 추출하기
mapdf=df[["상호","주소","상표", "휘발유"]]
mapdf.head()

                상호                      주소     상표   휘발유
0  지에스이앤알 직영 서울주유소    서울 양천구 신정로 236 (신정동)  GS칼텍스  1978
1          가로공원주유소  서울 양천구 가로공원로 165 (신월동)  SK에너지  1978
2            현대주유소  서울 양천구 남부순환로 372 (신월동)  S-OIL  1979
3   (주)타이거오일 신정주유소    서울 양천구 중앙로 226 (신정동)  SK에너지  1979
4            신월주유소    서울 양천구 신월로 193 (신월동)  GS칼텍스  1979

In [ ]:
# 주소에서 ()에 있는 데이터 제거
for i in range(len(mapdf)):
    mapdf.iloc[i,1]=mapdf.iloc[i,1].split("(")[0]

mapdf.head()

C:\Users\student\AppData\Local\Temp\ipykernel_2272\1717148473.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapdf.iloc[i,1]=mapdf.iloc[i,1].split("(")[0]

                상호                 주소     상표   휘발유
0  지에스이앤알 직영 서울주유소    서울 양천구 신정로 236   GS칼텍스  1978
1          가로공원주유소  서울 양천구 가로공원로 165   SK에너지  1978
2            현대주유소  서울 양천구 남부순환로 372   S-OIL  1979
3   (주)타이거오일 신정주유소    서울 양천구 중앙로 226   SK에너지  1979
4            신월주유소    서울 양천구 신월로 193   GS칼텍스  1979

In [ ]:
# 주소에서 ()에 있는 데이터 제거(권장)
for i in mapdf.index:
    mapdf.loc[i,"주소"]=mapdf.loc[i,"주소"].split("(")[0]

mapdf.head()

C:\Users\student\AppData\Local\Temp\ipykernel_2272\3931679002.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapdf.loc[i,"주소"]=mapdf.loc[i,"주소"].split("(")[0]

                상호                 주소     상표   휘발유
0  지에스이앤알 직영 서울주유소    서울 양천구 신정로 236   GS칼텍스  1978
1          가로공원주유소  서울 양천구 가로공원로 165   SK에너지  1978
2            현대주유소  서울 양천구 남부순환로 372   S-OIL  1979
3   (주)타이거오일 신정주유소    서울 양천구 중앙로 226   SK에너지  1979
4            신월주유소    서울 양천구 신월로 193   GS칼텍스  1979

In [ ]:
# 구글 API를 이용한 주소 검색(위도/경도 추출)
user_Key='AIzaSyB8Ua6RAi-ZC5WoE4xbEtlnEWZ_XOpaWGk'
gmaps=googlemaps.Client(key=user_Key)

ggmap=gmaps.geocode("서울 양천구 신정로 236", language='ko')
lat=ggmap[-1]['geometry']['location']['lat']
lng=ggmap[-1]['geometry']['location']['lng']
print(lat, lng)

37.5105184 126.8476876

In [ ]:
# mapdf의 주소를 이용해 위도/경도 필트 추가

lat=[];lng=[]

for i in mapdf.index:
    ggmap=gmaps.geocode(mapdf.loc[i,"주소"], language='ko')
    lat.append(ggmap[-1]['geometry']['location']['lat'])
    lng.append(ggmap[-1]['geometry']['location']['lng'])

mapdf['위도']=lat
mapdf['경도']=lng
mapdf.head()

C:\Users\student\AppData\Local\Temp\ipykernel_2272\2888899339.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapdf['위도']=lat
C:\Users\student\AppData\Local\Temp\ipykernel_2272\2888899339.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapdf['경도']=lng

                상호                 주소     상표   휘발유         위도          경도
0  지에스이앤알 직영 서울주유소    서울 양천구 신정로 236   GS칼텍스  1978  37.510518  126.847688
1          가로공원주유소  서울 양천구 가로공원로 165   SK에너지  1978  37.536940  126.834278
2            현대주유소  서울 양천구 남부순환로 372   S-OIL  1979  37.533811  126.829240
3   (주)타이거오일 신정주유소    서울 양천구 중앙로 226   SK에너지  1979  37.516768  126.854657
4            신월주유소    서울 양천구 신월로 193   GS칼텍스  1979  37.520014  126.844069

In [ ]:
# 주유소 1개 출력
m=folium.Map(location=[37.5373614, 127.1244733], zoom_start=13)

folium.Marker([mapdf.loc[75, "위도"], mapdf.loc[75, "경도"]],
               popup=mapdf.loc[75, "상호"],
               icon=folium.Icon(color='red')).add_to(m)
m