### pandas 모듈
 - https://pandas.pydata.org/docs/user_guide/index.html
 - 사용하려면 기본적으로 사용하려면 (특히 오프라인) 무조건 설치 후 연결해서 사용
    ! pip install pandas
    import pandas as pd
- pandas에서 자주 사용하는 데이터 오브젝트
  * Series(1차원 배열) / DataFrame (2차원 배열)

In [ ]:
import pandas as pd
import numpy as np # 과학기술 관련 모듈 (계산용)

In [ ]:
#pandas.Series([값]): 리스트 내의 값들을 1차원 형태의 데이터 값을 형성
ser = pd.Series([1,3,5,np.nan,6,9]) #np.nan: numpy에서 null값 만든거
print(ser) #Seires는 1차원 구조를 의미
print(ser[:2])
print(type(ser))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    9.0
dtype: float64
0    1.0
1    3.0
dtype: float64
<class 'pandas.core.series.Series'>

- pandas.Series 클래스 구조

- pandas.DataFrame 클래스 구조
  * pandas.DataFrame(data=None,index=None,columns=None)
  * data:ndarray(배열),딕셔너리,DataFrame
  * index: 인덱스 또는 배열 형태의 객체, 생략 시 자동 생성 (0 ~ 1씩 증가)
  * columns: 열 index (생략 시 0부터 1씩 증가하면서 자동 생성)

In [ ]:
# DataFrame 생성
# pandas.date_range("시작일",periods=숫자) : 시작일에서 입력한 숫자만큼 날짜를 발생시키는 함수

date_lst=pd.date_range("20220301",periods=6)
print(date_lst)

DatetimeIndex(['2022-03-01', '2022-03-02', '2022-03-03', '2022-03-04',
               '2022-03-05', '2022-03-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# numpy.random.randn(6,4) // randn(행, 열) 행 개수 / 열 개수 정의
data=np.random.randn(6,4)
print(data)

[[-1.03777627  0.22071478 -0.11594247  1.29802422]
 [ 0.74300219  1.25202468 -1.39021247 -0.50832534]
 [-0.98987338  1.44723289 -0.39515226  0.32817077]
 [ 0.1503717  -1.80588133  1.200685   -0.44338285]
 [-0.08150294  2.54636893 -0.28121244 -0.09851826]
 [-0.20073601  1.40552359  0.59850143 -0.11253355]]

In [ ]:
# DataFrame 생성 (배열(리스트))
df1 = pd.DataFrame(data)
display(df1)

          0         1         2         3
0 -1.037776  0.220715 -0.115942  1.298024
1  0.743002  1.252025 -1.390212 -0.508325
2 -0.989873  1.447233 -0.395152  0.328171
3  0.150372 -1.805881  1.200685 -0.443383
4 -0.081503  2.546369 -0.281212 -0.098518
5 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
df1 = pd.DataFrame(data,columns=["a","b","c","d"])
display(df1)

          a         b         c         d
0 -1.037776  0.220715 -0.115942  1.298024
1  0.743002  1.252025 -1.390212 -0.508325
2 -0.989873  1.447233 -0.395152  0.328171
3  0.150372 -1.805881  1.200685 -0.443383
4 -0.081503  2.546369 -0.281212 -0.098518
5 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
df1 = pd.DataFrame(data,columns=["a","b","c","d"],index=date_lst) #columns, index 순서는 가리지 않음
display(df1)

                   a         b         c         d
2022-03-01 -1.037776  0.220715 -0.115942  1.298024
2022-03-02  0.743002  1.252025 -1.390212 -0.508325
2022-03-03 -0.989873  1.447233 -0.395152  0.328171
2022-03-04  0.150372 -1.805881  1.200685 -0.443383
2022-03-05 -0.081503  2.546369 -0.281212 -0.098518
2022-03-06 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
df1.index #df1에 정의된 index 속성값 출력

DatetimeIndex(['2022-03-01', '2022-03-02', '2022-03-03', '2022-03-04',
               '2022-03-05', '2022-03-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# pandas.DataFrame(딕셔너리)
dic1={'A':1.,
      "B":pd.Series(3, index=list(range(4)), dtype="float32"),
      "C":['2022-03-01', '2022-03-02', '2022-03-03', '2022-03-04'],
      "D":np.array([3]*4, dtype="int64"),
      "E":"python"}

df2=pd.DataFrame(dic1)
df2

     A    B           C  D       E
0  1.0  3.0  2022-03-01  3  python
1  1.0  3.0  2022-03-02  3  python
2  1.0  3.0  2022-03-03  3  python
3  1.0  3.0  2022-03-04  3  python

In [ ]:
df2.dtypes # DataFrame에서 구조의 각 열에 대한 데이터 타입을 확인

A    float64
B    float32
C     object
D      int64
E     object
dtype: object

In [ ]:
# 데이터 확인하기(df.head(), df.tail()) / 기본 5개 출력
display(df1.head(2))
display(df1.tail(1))

                   a         b         c         d
2022-03-01 -1.037776  0.220715 -0.115942  1.298024
2022-03-02  0.743002  1.252025 -1.390212 -0.508325

                   a         b         c         d
2022-03-06 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
# DataFrame 기본 속성
print(df1.index) # index 출력
print(df1.columns) # 열 이름 값 출력
print(df1.values) # 입력 데이터 출력

DatetimeIndex(['2022-03-01', '2022-03-02', '2022-03-03', '2022-03-04',
               '2022-03-05', '2022-03-06'],
              dtype='datetime64[ns]', freq='D')
Index(['a', 'b', 'c', 'd'], dtype='object')
[[-1.03777627  0.22071478 -0.11594247  1.29802422]
 [ 0.74300219  1.25202468 -1.39021247 -0.50832534]
 [-0.98987338  1.44723289 -0.39515226  0.32817077]
 [ 0.1503717  -1.80588133  1.200685   -0.44338285]
 [-0.08150294  2.54636893 -0.28121244 -0.09851826]
 [-0.20073601  1.40552359  0.59850143 -0.11253355]]

In [ ]:
# 숫자 데이터에 대한 기술통계 확인: df.describe()
# columns 별로 데이터 개수, 평균, 표준편차, 최소값, 4분위수(25%,50%,75%), 최대값
df1.describe() #숫자 데이터에 대해서만 반응한다

              a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean  -0.236086  0.844331 -0.063889  0.077239
std    0.684691  1.493593  0.889575  0.668449
min   -1.037776 -1.805881 -1.390212 -0.508325
25%   -0.792589  0.478542 -0.366667 -0.360671
50%   -0.141119  1.328774 -0.198577 -0.105526
75%    0.092403  1.436806  0.419890  0.221499
max    0.743002  2.546369  1.200685  1.298024

In [ ]:
df1.T #입력된 데이터의 행/열의 위치를 변경 --> 별도로 저장해야 됨

   2022-03-01  2022-03-02  2022-03-03  2022-03-04  2022-03-05  2022-03-06
a   -1.037776    0.743002   -0.989873    0.150372   -0.081503   -0.200736
b    0.220715    1.252025    1.447233   -1.805881    2.546369    1.405524
c   -0.115942   -1.390212   -0.395152    1.200685   -0.281212    0.598501
d    1.298024   -0.508325    0.328171   -0.443383   -0.098518   -0.112534

In [ ]:
# 데이터에 대한 정렬(index값)
df1.sort_index(ascending=True) #ascending=True(오름차순) / ascending=False(내림차순)
df1.sort_index(ascending=False)

                   a         b         c         d
2022-03-06 -0.200736  1.405524  0.598501 -0.112534
2022-03-05 -0.081503  2.546369 -0.281212 -0.098518
2022-03-04  0.150372 -1.805881  1.200685 -0.443383
2022-03-03 -0.989873  1.447233 -0.395152  0.328171
2022-03-02  0.743002  1.252025 -1.390212 -0.508325
2022-03-01 -1.037776  0.220715 -0.115942  1.298024

In [ ]:
# 데이터에 대한 정렬(values 값)
df1.sort_values(by="c",ascending=False) # c열을 기준으로 내림차순 정렬 (오름차순 여부는 생략 가능)
df1.sort_values(by="c",ascending=True) # c열 기준 오름차순 정렬

                   a         b         c         d
2022-03-02  0.743002  1.252025 -1.390212 -0.508325
2022-03-03 -0.989873  1.447233 -0.395152  0.328171
2022-03-05 -0.081503  2.546369 -0.281212 -0.098518
2022-03-01 -1.037776  0.220715 -0.115942  1.298024
2022-03-06 -0.200736  1.405524  0.598501 -0.112534
2022-03-04  0.150372 -1.805881  1.200685 -0.443383

### DF 형식의 데이터 선택

In [ ]:
# 특정 열(필드) 하나만 출력하기
df1['a']
print(df1.a)
print(type(df1.a))

2022-03-01   -1.037776
2022-03-02    0.743002
2022-03-03   -0.989873
2022-03-04    0.150372
2022-03-05   -0.081503
2022-03-06   -0.200736
Freq: D, Name: a, dtype: float64
<class 'pandas.core.series.Series'>

In [ ]:
df1[0:3] # 첫번째부터 3개의 행을 출력 / iloc[0:3]과 같음
df1["2022-03-02":"2022-03-04"] #입력한 index의 시작~종료값 사이의 데이터 출력 / loc[시작:종료]

                   a         b         c         d
2022-03-02  0.743002  1.252025 -1.390212 -0.508325
2022-03-03 -0.989873  1.447233 -0.395152  0.328171
2022-03-04  0.150372 -1.805881  1.200685 -0.443383

- DataFrame.loc[ ]: index값 중심으로 데이터 선택

In [ ]:
#df1.loc[index 값]
df1.loc["2022-03-01"]
df1.loc["20220301"]

In [ ]:
# loc[]에서 원하는 컬럼 지정
df1.loc["20220303":"20220304",['b','c']] # df1에서 b와 c열의 데이터만 출력

                   b         c
2022-03-03  1.447233 -0.395152
2022-03-04 -1.805881  1.200685

- DataFrame.iloc[ ]: 데이터의 위치값을 이용해 선택

In [ ]:
df1.iloc[0] #df1에서 0번째 데이터 출력 (0번째 위치한 값)

a   -1.037776
b    0.220715
c   -0.115942
d    1.298024
Name: 2022-03-01 00:00:00, dtype: float64

In [ ]:
df1.iloc[2:4,0:2] # 행: 2~3행, 열은 0~1열까지 (연속된 행, 열 값 출력)

                   a         b
2022-03-03 -0.989873  1.447233
2022-03-04  0.150372 -1.805881

In [ ]:
df1.iloc[[1,3,5],[1,3]] # 행/열 기준으로 떨어져 있는 값 출력 가능 (인덱스나 열 이름 쓰면 안 됨)

                   b         d
2022-03-02  1.252025 -0.508325
2022-03-04 -1.805881 -0.443383
2022-03-06  1.405524 -0.112534

In [ ]:
# 주의할 점
df1.iloc[[3,5],[0:2]] # 연속 범위와 떨어진 범위를 동시에 설정 불가

- 조건을 이용한 데이터 추출
    단일조건: df[df["필드명"] >  '기준값']/
    df[df.필드명 > 기준값] /

    다중 조건: df[(조건식1)&(조건식2)] / df[(조건식1) | (조건식2)] (&; and 연산, |: or연산)

In [ ]:
df1[df1.c >= 0] # 단일조건: c열의 값이 0보다 큰 값

                   a         b         c         d
2022-03-04  0.150372 -1.805881  1.200685 -0.443383
2022-03-06 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
# 다중 조건에 대한 and 연산 (&)
df1[(df1.b>0)&(df1['c']>0)] #b열과 c열의 값이 모두 0보다 큰 값 출력

                   a         b         c         d
2022-03-06 -0.200736  1.405524  0.598501 -0.112534

In [ ]:
# 다중 조건에 대한 or 연산(|)
df1[(df1.b<0)|(df1['c']>0)] # b열이 0보다 작거나, c열이 0보다 큰 값 모두 출력

                   a         b         c         d
2022-03-04  0.150372 -1.805881  1.200685 -0.443383
2022-03-06 -0.200736  1.405524  0.598501 -0.112534

- DataFrame 복사 및 새로운 열 추가
  * 복사: df2=df1.copy()
  * 열 추가: df2['열 이름'] = [리스트형 데이터]

In [ ]:
# df1의 데이터 개수
len(df1) # df1의 행의 개수

6

In [ ]:
# df1을 df2로 복사하고 df2에 새로운 필드(열) 추가
df2 = df1.copy()
df3 = df1

display(df2)
display(df3)

In [ ]:
df2['e'] = ['aa','bb','aa','cc','bb','ff']
display(df1)
display(df2)

In [ ]:
df3['e'] = ['aa','bb','aa','cc','bb','ff']
display(df3)

In [ ]:
#del df1['e'] # del 객체 삭제

display(df2)

                   a         b         c         d   e
2022-03-01 -1.037776  0.220715 -0.115942  1.298024  aa
2022-03-02  0.743002  1.252025 -1.390212 -0.508325  bb
2022-03-03 -0.989873  1.447233 -0.395152  0.328171  aa
2022-03-04  0.150372 -1.805881  1.200685 -0.443383  cc
2022-03-05 -0.081503  2.546369 -0.281212 -0.098518  bb
2022-03-06 -0.200736  1.405524  0.598501 -0.112534  ff

In [ ]:
df2[df2['e'].isin(['cc','ff'])] # e열에 'cc','ff'가 있는 모든 값 출력

                   a         b         c         d   e
2022-03-04  0.150372 -1.805881  1.200685 -0.443383  cc
2022-03-06 -0.200736  1.405524  0.598501 -0.112534  ff

In [ ]:
df2[df2['e'].isin(['cc','ff'])][['c','d']]

                   c         d
2022-03-04  1.200685 -0.443383
2022-03-06  0.598501 -0.112534

In [ ]:
df2.loc[df2['e'] == 'aa',['c','d']] #e열이 'aa'인 값 중 'c'와 'd'열만 출력하겠다

                   c         d
2022-03-01 -0.115942  1.298024
2022-03-03 -0.395152  0.328171

In [ ]:
df2.loc[(df2['e'] == 'aa')|(df2['e'] == 'bb'),['c','d']]
#e열이 'aa' 또는 'bb'인 값 중 'c'와 'd'열만 출력하겠다

In [ ]:
# 데이터 수정(특정 위치에 있는)
df2.loc[df2['e'] == 'aa','c'] = 0
df2

                   a         b         c         d   e
2022-03-01 -1.037776  0.220715  0.000000  1.298024  aa
2022-03-02  0.743002  1.252025 -1.390212 -0.508325  bb
2022-03-03 -0.989873  1.447233  0.000000  0.328171  aa
2022-03-04  0.150372 -1.805881  1.200685 -0.443383  cc
2022-03-05 -0.081503  2.546369 -0.281212 -0.098518  bb
2022-03-06 -0.200736  1.405524  0.598501 -0.112534  ff

csv 읽어오기

- pandas.read_csv("경로/파일명.csv" , header = none)

In [ ]:
# csv 파일(지역_위치별(주유소)) 읽어오기

df1=pd.read_csv("/content/data/지역_위치별(주유소).csv")
df1.head()

,지역_위치별(주유소),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(단위 : 원/리터)
1,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
2,서울특별시,성산주유소,서울 마포구 월드컵북로 170 (성산제2동),SK에너지,02-373-3314,N,NaN,1987,1877,-
3,서울특별시,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,NaN,1988,1865,1598
4,서울특별시,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198,1988,1865,-

In [ ]:
df1=pd.read_csv("/content/data/지역_위치별(주유소)(4).csv",header=2, encoding='cp949') #위에서 2줄 제외
display(df1.head(3))

df2=pd.read_csv("/content/data/지역_위치별(주유소).csv",header=2, encoding='utf-8')
display(df2.head(3))

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,수유동주유소,서울 강북구 도봉로 395 (수유동),GS칼텍스,02-902-9470,Y,-,1989,1889,-
1,서울특별시,대성석유(주)신광주유소,서울 강북구 삼양로 484,GS칼텍스,02-908-3320,N,-,1995,1895,1500
2,서울특별시,세원주유소,서울 강북구 한천로 918 (번동),SK에너지,02-907-6890,Y,-,1998,1898,1400

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,성산주유소,서울 마포구 월드컵북로 170 (성산제2동),SK에너지,02-373-3314,N,NaN,1987,1877,-
1,서울특별시,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,NaN,1988,1865,1598
2,서울특별시,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198.0,1988,1865,-

In [ ]:
# 데이터 갯수 확인하기
print(len(df1))

13

In [ ]:
print(df1.count()) # 각 필드 단위로 몇 개의 데이터를 갖고 있는 지 표시

지역       13
상호       13
주소       13
상표       13
전화번호     13
셀프여부     13
고급휘발유    13
휘발유      13
경유       13
실내등유     13
dtype: int64

In [ ]:
print(df2.count())

지역       12
상호       12
주소       12
상표       12
전화번호     12
셀프여부     12
고급휘발유     5
휘발유      12
경유       12
실내등유     12
dtype: int64

- DataFrame 전체 정보 확인
  * df.info()

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      13 non-null     object
 1   상호      13 non-null     object
 2   주소      13 non-null     object
 3   상표      13 non-null     object
 4   전화번호    13 non-null     object
 5   셀프여부    13 non-null     object
 6   고급휘발유   13 non-null     object
 7   휘발유     13 non-null     int64
 8   경유      13 non-null     int64
 9   실내등유    13 non-null     object
dtypes: int64(2), object(8)
memory usage: 1.1+ KB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      12 non-null     object
 1   상호      12 non-null     object
 2   주소      12 non-null     object
 3   상표      12 non-null     object
 4   전화번호    12 non-null     object
 5   셀프여부    12 non-null     object
 6   고급휘발유   5 non-null      float64
 7   휘발유     12 non-null     int64
 8   경유      12 non-null     int64
 9   실내등유    12 non-null     object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.1+ KB

- 데이터에서 NaN 값 확인하기
  * NaN: 결측지 (데이터의 입력 값이 없을 때)
  * 결측지 처리: 삭제 / 위 또는 아래값으로 채우기 / 전체 평균값으로 채우기
  * NaN 확인법: isna() => NaN인지 아닌지를 True/False로 반환

In [ ]:
display(df2.isna())

       지역     상호     주소     상표   전화번호   셀프여부  고급휘발유    휘발유     경유   실내등유
0   False  False  False  False  False  False   True  False  False  False
1   False  False  False  False  False  False   True  False  False  False
2   False  False  False  False  False  False  False  False  False  False
3   False  False  False  False  False  False   True  False  False  False
4   False  False  False  False  False  False   True  False  False  False
5   False  False  False  False  False  False  False  False  False  False
6   False  False  False  False  False  False   True  False  False  False
7   False  False  False  False  False  False   True  False  False  False
8   False  False  False  False  False  False  False  False  False  False
9   False  False  False  False  False  False  False  False  False  False
10  False  False  False  False  False  False  False  False  False  False
11  False  False  False  False  False  False   True  False  False  False

In [ ]:
df2.isna().sum() # 반환된 True/False 중 True의 값만 count

지역       0
상호       0
주소       0
상표       0
전화번호     0
셀프여부     0
고급휘발유    7
휘발유      0
경유       0
실내등유     0
dtype: int64

In [ ]:
# DataFrame 데이터 삭제하기: drop() 함수를 이용한다
df3 = df2.copy()


# index를 이용하여 삭제하는 방법
#df3=df3.drop(index=0, axis=0) # axis = 0 이면 행 삭제 / axis=1이면 열 삭제
df3.drop(index=0, axis=0,inplace=True) # 바로 위랑 같은 의미
df3

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
1,서울특별시,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,NaN,1988,1865,1598
2,서울특별시,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198.0,1988,1865,-
3,서울특별시,마포시엠주유소,서울 마포구 월드컵북로62 (성산동),GS칼텍스,02-336-1687,N,NaN,1997,1897,-
4,서울특별시,(주)안국에너지 망원동주유소,서울 마포구 월드컵로 119 (망원동),SK에너지,02-334-0917,N,NaN,1998,1898,-
5,서울특별시,에스에스오토셀프,서울 마포구 서강로 76 (창전동),현대오일뱅크,02-336-5185,Y,2294.0,2039,1929,-
6,서울특별시,에스오일(주) 염리동주유소,서울 마포구 백범로 126 (염리동),S-OIL,02-3272-5155,Y,NaN,2039,1929,-
7,서울특별시,용강주유소,서울 마포구 토정로 258,S-OIL,070-7795-4800,N,NaN,2059,1949,1350
8,서울특별시,대흥주유소,서울 마포구 대흥로 61 (대흥동),SK에너지,02-3273-5151,N,2316.0,2069,1959,1699
9,서울특별시,SK에너지(주) 안국주유소,서울 마포구 양화로 33 (합정동),SK에너지,02-3144-1197,N,2299.0,2199,2139,-
10,서울특별시,SK에너지 양지주유소,서울 마포구 마포대로 69 (도화동),SK에너지,02-706-8955,N,2299.0,2199,2169,-
11,서울특별시,마포주유소,서울 마포구 마포대로 186 (공덕동),S-OIL,02-701-3990,N,NaN,2299,2198,1647

In [ ]:
# 열 삭제: del df[["열 이름1"],["열 이름2"]] / drop(["필드 명"],axis = 1, inplace=True)
df3=df3.drop(["지역","실내등유"],axis=1)
df3.head()

,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유
1,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,NaN,1988,1865
2,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198.0,1988,1865
3,마포시엠주유소,서울 마포구 월드컵북로62 (성산동),GS칼텍스,02-336-1687,N,NaN,1997,1897
4,(주)안국에너지 망원동주유소,서울 마포구 월드컵로 119 (망원동),SK에너지,02-334-0917,N,NaN,1998,1898
5,에스에스오토셀프,서울 마포구 서강로 76 (창전동),현대오일뱅크,02-336-5185,Y,2294.0,2039,1929

- 데이터에서 NaN 값 제거하기
  * df.dropna(): 1개라도 NaN 있는 행 모두 제거
  * df.dropna(axis=1): NaN이 1개라도 있는 열 삭제
  * df.dropna(how='all'): 행 전체가 NaN이면 해당 행 삭제
  * df.dropna(thresh=n): 각 행에 대해 n개 이상의 값을 가진 데이터만 출력
  * df.dropna(subset=['열이름','열이름'..]): 지정한 열의 값이 NaN이면 해당 행 삭제

In [ ]:
df3.dropna(axis=1)

,상호,주소,상표,전화번호,셀프여부,휘발유,경유
1,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,1988,1865
2,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,1988,1865
3,마포시엠주유소,서울 마포구 월드컵북로62 (성산동),GS칼텍스,02-336-1687,N,1997,1897
4,(주)안국에너지 망원동주유소,서울 마포구 월드컵로 119 (망원동),SK에너지,02-334-0917,N,1998,1898
5,에스에스오토셀프,서울 마포구 서강로 76 (창전동),현대오일뱅크,02-336-5185,Y,2039,1929
6,에스오일(주) 염리동주유소,서울 마포구 백범로 126 (염리동),S-OIL,02-3272-5155,Y,2039,1929
7,용강주유소,서울 마포구 토정로 258,S-OIL,070-7795-4800,N,2059,1949
8,대흥주유소,서울 마포구 대흥로 61 (대흥동),SK에너지,02-3273-5151,N,2069,1959
9,SK에너지(주) 안국주유소,서울 마포구 양화로 33 (합정동),SK에너지,02-3144-1197,N,2199,2139
10,SK에너지 양지주유소,서울 마포구 마포대로 69 (도화동),SK에너지,02-706-8955,N,2199,2169
11,마포주유소,서울 마포구 마포대로 186 (공덕동),S-OIL,02-701-3990,N,2299,2198

- 결측지 값 변경
  * df.fillna('값'): 모든 NaN을 입력 값으로 변경
  * df.replace(numpy.nan,0): numpy 모듈을 이용한 변경

In [ ]:
# DataFrame 계산
sum1 = df3['고급휘발유'].sum() # 고급 휘발유 필드 전체 합계
mean1 = df3['고급휘발유'].mean() # 고급 휘발유 필드 전체 평균
print(f"고급휘발유 합계 :{sum1}, 평균:{mean1}")

고급휘발유 합계 :11406.0, 평균:2281.2

In [ ]:
# 고급 휘발유의 NaN 값을 평균값으로 채우기
# df3.fillna(mean1) => inplace=False (df3에 데이터를 전달해주지는 않는다. 결과는 나옴)
df3.fillna(mean1, inplace = True) # df3 = df3.fillna(mean1)
df3

,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유
1,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,2281.2,1988,1865
2,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198.0,1988,1865
3,마포시엠주유소,서울 마포구 월드컵북로62 (성산동),GS칼텍스,02-336-1687,N,2281.2,1997,1897
4,(주)안국에너지 망원동주유소,서울 마포구 월드컵로 119 (망원동),SK에너지,02-334-0917,N,2281.2,1998,1898
5,에스에스오토셀프,서울 마포구 서강로 76 (창전동),현대오일뱅크,02-336-5185,Y,2294.0,2039,1929
6,에스오일(주) 염리동주유소,서울 마포구 백범로 126 (염리동),S-OIL,02-3272-5155,Y,2281.2,2039,1929
7,용강주유소,서울 마포구 토정로 258,S-OIL,070-7795-4800,N,2281.2,2059,1949
8,대흥주유소,서울 마포구 대흥로 61 (대흥동),SK에너지,02-3273-5151,N,2316.0,2069,1959
9,SK에너지(주) 안국주유소,서울 마포구 양화로 33 (합정동),SK에너지,02-3144-1197,N,2299.0,2199,2139
10,SK에너지 양지주유소,서울 마포구 마포대로 69 (도화동),SK에너지,02-706-8955,N,2299.0,2199,2169
11,마포주유소,서울 마포구 마포대로 186 (공덕동),S-OIL,02-701-3990,N,2281.2,2299,2198

In [ ]:
# 새로운 계산필드 생성
mean2 = df3["휘발유"].mean() #휘발유 값의 평균
print(mean2)
print(df3.iloc[-1,-2] - mean2)
print(df3.loc[11,['휘발유']] - mean2)

2079.4545454545455
219.5454545454545
휘발유    219.545455
Name: 11, dtype: object

In [ ]:
# "평균 대비" 필드에 추가
# df['새로운 필드명'] = [값]. [값]은 df의 데이터 개수와 일치시켜줘야 한다
# new_val 값 생성
# 1. new_val 변수 생성 / 2. new_val 변수에 평균 휘발유값 - 행별 휘발유 값 추가
# 3. df3["평균대비"] 필드 생성 후 new_val 값을 대입

new_val=[]
for i in df3.index:
    new_val.append(df3.loc[i, "휘발유"]-mean2)

df3["평균대비"] = new_val
df3.head()

,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,평균대비
1,성산대교셀프주유소,서울 마포구 성산로 144,현대오일뱅크,02-323-0078,Y,2281.2,1988,1865,-91.454545
2,청원주유소,서울 마포구 월드컵북로 113 (성산동),현대오일뱅크,02-325-5533,Y,2198.0,1988,1865,-91.454545
3,마포시엠주유소,서울 마포구 월드컵북로62 (성산동),GS칼텍스,02-336-1687,N,2281.2,1997,1897,-82.454545
4,(주)안국에너지 망원동주유소,서울 마포구 월드컵로 119 (망원동),SK에너지,02-334-0917,N,2281.2,1998,1898,-81.454545
5,에스에스오토셀프,서울 마포구 서강로 76 (창전동),현대오일뱅크,02-336-5185,Y,2294.0,2039,1929,-40.454545

In [ ]:
place1=[]
for i in range(len(df3)):
  place1.append(df3.iloc[i,1].split(" ")[1])

df3["구"] = place1

df3[['상표','주소','구','휘발유','경유','셀프여부']].head()

       상표                      주소    구   휘발유    경유 셀프여부
1  현대오일뱅크          서울 마포구 성산로 144  마포구  1988  1865    Y
2  현대오일뱅크  서울 마포구 월드컵북로 113 (성산동)  마포구  1988  1865    Y
3   GS칼텍스    서울 마포구 월드컵북로62 (성산동)  마포구  1997  1897    N
4   SK에너지   서울 마포구 월드컵로 119 (망원동)  마포구  1998  1898    N
5  현대오일뱅크     서울 마포구 서강로 76 (창전동)  마포구  2039  1929    Y

- pandas 데이터 병합 / 연결
  * DataFrame 병합: merge()

In [ ]:
df1 = pd.DataFrame({'고객번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']},
    columns=['고객번호', '이름'])
df1

   고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [ ]:
df2 = pd.DataFrame({'고객번호': [1001, 1001, 1005, 1006, 1008, 1001],
    '금액': [10000, 20000, 15000, 5000, 100000, 30000]}, columns=['고객번호', '금액'])
df2

   고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

In [ ]:
pd.merge(df1,df2) # df1과 df2의 공통열을 기준으로 데이터를 찾아서 붙여준다
# 공통으로 존재하는 데이터 (고객번호)기준으로 묶어줌

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [ ]:
pd.merge(df1,df2,how='outer')
# df1, df2의 모든 데이터를 출력

   고객번호   이름        금액
0  1001   둘리   10000.0
1  1001   둘리   20000.0
2  1001   둘리   30000.0
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동   15000.0
7  1006  마이콜    5000.0
8  1007   영희       NaN
9  1008  NaN  100000.0

In [ ]:
# df1, df2에서 왼쪽에 위치한 데이터를 기준으로 출력
pd.merge(df1,df2,how='left')

   고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN

In [ ]:
# df1, df2에서 오른쪽에 위치한 데이터를 기준으로 출력
pd.merge(df1,df2,how='right')

   고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

- DataFrame 데이터 연결 (데이터를 기존 데이터의 아래에 추가할 때)
  * concat 함수
  * df.concat([df1,df2,df3, ...]): 열 제목을 기준으로 아래에 추가
  * df.concat([df1,df2,df3, ...],axis=1): index 값을 기준으로 뒤(오른쪽)에 붙여준다.

In [ ]:
df1=pd.DataFrame({"이름":["홍길동","이순신","김파이","장길산"],"나이":[30,45,29,48],"성적":[99,88,77,66]})

df1

    이름  나이  성적
0  홍길동  30  99
1  이순신  45  88
2  김파이  29  77
3  장길산  48  66

In [ ]:
df2=pd.DataFrame({"이름":["박노트","이상식","조규식","서준석"],"나이":[74,88,68,59],"성적":[88,77,88,92]})

df2

    이름  나이  성적
0  박노트  74  88
1  이상식  88  77
2  조규식  68  88
3  서준석  59  92

In [ ]:
df3=pd.DataFrame({"이름":["박지정","김규식","홍규식","차준석"],
                  "나이":[74,88,68,59],"성적":[88,77,88,92],"비고":["간","폐","위","간"]},)

df3

    이름  나이  성적 비고
0  박지정  74  88  간
1  김규식  88  77  폐
2  홍규식  68  88  위
3  차준석  59  92  간

In [ ]:
# 데이터의 열 이름이 동일한 경우
pd.concat([df1,df2])

    이름  나이  성적
0  홍길동  30  99
1  이순신  45  88
2  김파이  29  77
3  장길산  48  66
0  박노트  74  88
1  이상식  88  77
2  조규식  68  88
3  서준석  59  92

In [ ]:
# 필드명이 다른 데이터 추가했을 때 (concat)
pd.concat([df1,df3])

    이름  나이  성적   비고
0  홍길동  30  99  NaN
1  이순신  45  88  NaN
2  김파이  29  77  NaN
3  장길산  48  66  NaN
0  박지정  74  88    간
1  김규식  88  77    폐
2  홍규식  68  88    위
3  차준석  59  92    간

In [ ]:
# concat은 2개 이상의 DataFrame을 한 번에 합칠 수 있다.
pd.concat([df1,df2,df3])

    이름  나이  성적   비고
0  홍길동  30  99  NaN
1  이순신  45  88  NaN
2  김파이  29  77  NaN
3  장길산  48  66  NaN
0  박노트  74  88  NaN
1  이상식  88  77  NaN
2  조규식  68  88  NaN
3  서준석  59  92  NaN
0  박지정  74  88    간
1  김규식  88  77    폐
2  홍규식  68  88    위
3  차준석  59  92    간

In [ ]:
### concat 열 추가
df1=pd.DataFrame([["홍길동", 25, "남"], ["이순신", 48, "남"], ["유관순", 18, "여"]],
                 columns=["이름", "나이", "성별"])
df1

    이름  나이 성별
0  홍길동  25  남
1  이순신  48  남
2  유관순  18  여

In [ ]:
df2=pd.DataFrame([[85,76,88,"-"],[45,76,65,"관심"],[88,75,91,"-"],[60,60,60,"-"]],
                 columns=["국어", "영어", "수학", "비고"])

df2=df2.drop(1)
df2

   국어  영어  수학 비고
0  85  76  88  -
2  88  75  91  -
3  60  60  60  -

In [ ]:
pd.concat([df1,df2],axis=1)

    이름    나이   성별    국어    영어    수학   비고
0  홍길동  25.0    남  85.0  76.0  88.0    -
1  이순신  48.0    남   NaN   NaN   NaN  NaN
2  유관순  18.0    여  88.0  75.0  91.0    -
3  NaN   NaN  NaN  60.0  60.0  60.0    -

### 서울시 유가정보 가져와서 1개 파일로 합치기
1. '/content' 폴더의 'data' 폴더 생성 후 파일 업로드
2. data 폴더에 있는 데이터 읽어온 다음에 oildf에 모두 저장
3. 데이터는 concat()을 이용해 데이터 아래에 추가
4. encoding: cp949 또는 utf8 같이 있어 에러가 발생할 수 있음
  * try: ~ except: ~로 해결

- data 폴더에 있는 파일명/하위폴더명 가져오기 : os 모듈
- for 문을 이용해 첫번째 파일부터 순차적으로 읽어와 oildf에 concat 진행
- 파일 읽을 시 encoding 에러
  try:
    utf-8 형식 읽어오기
  except:
    cp949 형식 읽어오기
- 빈 DataFrame 변수 생성
  oildf=pd.DataFrame()

In [ ]:
# 서울시 유가정보 가져와 1개로 합치기
import os
# /content/data/지역_위치별(주유소)(2).csv

fnames = os.listdir("/content/data") # data 폴더 디렉토리 정의

oildf=pd.DataFrame() # 빈 데이터 프레임 만드는 거

for fname in fnames: # for문을 이용하여 폴더 안에 있는 모든 파일 불러오기
  try:
    df0 = pd.read_csv("/content/data"+fname,header=2, encoding='utf-8')
# df0에 csv 파일을 지정된 경로에 있는 파일을 utf-8 형식으로 불러와라
  except:
    df0 = pd.read_csv("/content/data"+fname,header=2, encoding='cp949')
# df0에 csv 파일을 cp949 형식으로 불러와라
    oildf=pd.concat([oildf,df0])

del df0 # 임시 데이터프레임 삭제
oildf.reset_index(drop=True, inplace=True) # oildf의 인덱스 재설정(기존에 있던 인덱스 삭제)

display(oildf.head(3))

oildf.info()

FileNotFoundError: ignored

### 데이터 전처리

In [ ]:
# 구 생성
gutxt = [] # 구 리스트를 새로 생성
for i in oildf.index:
   # 구 리스트에 주소를 넣을 건데
    gutxt.append(oildf.loc[i,"주소"].split(" ")[1]) # 각 행(인덱스)마다 주소를 " "으로 쪼개고 1번째 데이터 넣어
  # gutxt.append(oildf.iloc[i,["주소"]].split(" ")[1])
  #주소에 [] 지운 이유는 문자형으로 만들어야하기 때문에 (그냥 쓰면 series형이 되어 버림)
oildf["구"] = gutxt # oildf에 구라는 열을 생성하고 그 열에 gutxt의 값을 넣는다
oildf=oildf['상호','상표','구','셀프여부','휘발유','경유']
#oildf에 oildf 데이터프레임에 상호, 상표, 구, 셀프여부, 휘발유, 경유 저장

oildf.head(3)

In [ ]:
oildf['구'] = gutxt
oildf.columns


oildf = oildf[['상호','상표','구','셀프여부','휘발유','경유']]
oildf2 = oildf.iloc[:,[1,3,-1,5,7,8]]

oildf.head(3)
oildf2.head(3)

oildf2.dtypes

In [ ]:
oildf2=oildf.fillna("-") #NaN 값을 -로 변경
oildf['휘발유'].unique() # 고유값 찾기

In [ ]:
oildf2.astype({'휘발유':int, '경유':int}) # 오브젝트 변수를 정수로 변경

In [ ]:
oildf2['휘발유'].mean()

In [ ]:
oildf2.fillna()