### 데이터 전처리

###### 1. 데이터 인코딩

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [ ]:
# 레이블 인코더 객체 생성
le = LabelEncoder()

In [ ]:
# 학습시킬 데이터를 훑어보는 과정
le.fit(items)

LabelEncoder()

In [ ]:
# 인코딩 실행
labels=le.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 실전에서는 (fit과 transform을 한 번에)
le2 = LabelEncoder()
labels = le2.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 숙련자들은 한 줄로 끝낸다
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
le.inverse_transform([2,4,3,0,5,1]) # 디코딩

array(['믹서', '전자레인지', '선풍기', 'TV', '컴퓨터', '냉장고'], dtype='<U5')

###### 2. One - hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
oh_labels = ohe.fit_transform(labels.reshape(-1,1))
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [ ]:
from tensorflow.keras.utils import to_categorical
to_categorical(labels)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

###### 3. 표준화
 - 평균 0, 표준편차 1인 가우시안 표준 정규분포로 변환

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
from sklearn.preprocessing import StandardScaler
iris_std = StandardScaler().fit_transform(iris.data)

In [ ]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [ ]:
df = pd.DataFrame(iris_std, columns = iris.feature_names)
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-1.690315e-15,-1.842970e-15,-1.698641e-15,-1.409243e-15
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00

- Logistic Regression으로 분류

In [ ]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=2022)

In [ ]:
# 표준 정규분포로 변환된 데이터로 학습을 시키면 빨리 목표값에 도달
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_std, iris.target, stratify = iris.target, random_state=2022)

In [ ]:
lrc.fit(X_train, y_train)

LogisticRegression(random_state=2022)

In [ ]:
lrc.score(X_test, y_test)

0.9473684210526315

###### 4. 정규화
 - 최소값 0, 최대값 1로 변환

In [ ]:
from sklearn.preprocessing import MinMaxScaler
iris_mn = MinMaxScaler().fit_transform(iris.data)

In [ ]:
df3 = pd.DataFrame(iris_mn, columns = iris.feature_names)
df3.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,0.428704,0.440556,0.467458,0.458056
std,0.230018,0.181611,0.299203,0.317599
min,0.000000,0.000000,0.000000,0.000000
25%,0.222222,0.333333,0.101695,0.083333
50%,0.416667,0.416667,0.567797,0.500000
75%,0.583333,0.541667,0.694915,0.708333
max,1.000000,1.000000,1.000000,1.000000

In [ ]:
# 정규화된 데이터로 학습하면 빨리 목표값에 도달하여 에러가 발생하지 않음
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_mn, iris.target, stratify = iris.target, random_state=2022)

In [ ]:
lrc = LogisticRegression(random_state=2022)
lrc.fit(X_train, y_train)
lrc.score(X_test, y_test)

0.9210526315789473